"""add_domain_event

Revision ID: 572da3239ca3
Revises: 20250409_vendor_marketplace
Create Date: 2026-04-09 17:33:25.582384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '572da3239ca3'
down_revision: Union[str, Sequence[str], None] = '20250409_vendor_marketplace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('correlation_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_events_correlation_id'), 'domain_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_domain_events_event_type'), 'domain_events', ['event_type'], unique=False)
    op.drop_index(op.f('ix_customer_inquiries_created_at'), table_name='customer_inquiries')
    op.drop_index(op.f('ix_customer_inquiries_customer_email'), table_name='customer_inquiries')
    op.drop_index(op.f('ix_customer_inquiries_customer_name'), table_name='customer_inquiries')
    op.drop_index(op.f('ix_customer_inquiries_vendor_id'), table_name='customer_inquiries')
    op.drop_index(op.f('ix_customer_inquiries_vendor_id_status'), table_name='customer_inquiries')
    op.drop_table('customer_inquiries')
    op.drop_index(op.f('ix_approval_requests_status_submitted'), table_name='approval_requests')
    op.drop_index(op.f('ix_vendor_categories_category_id'), table_name='vendor_categories')
    op.drop_index(op.f('idx_vendors_description_fts'), table_name='vendors', postgresql_using='gin')
    op.drop_index(op.f('idx_vendors_description_trgm'), table_name='vendors', postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_vendors_name_fts'), table_name='vendors', postgresql_using='gin')
    op.drop_index(op.f('idx_vendors_name_trgm'), table_name='vendors', postgresql_ops={'business_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_vendors_business_name_location'), table_name='vendors', postgresql_where="(status <> 'REJECTED'::vendor_status_enum)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_vendors_business_name_location'), 'vendors', [sa.literal_column("lower('business_name'::text)"), sa.literal_column("lower('city'::text)"), sa.literal_column("lower('region'::text)")], unique=True, postgresql_where="(status <> 'REJECTED'::vendor_status_enum)")
    op.create_index(op.f('idx_vendors_name_trgm'), 'vendors', ['business_name'], unique=False, postgresql_ops={'business_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_vendors_name_fts'), 'vendors', [sa.literal_column("to_tsvector('english'::regconfig, business_name::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_vendors_description_trgm'), 'vendors', ['description'], unique=False, postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_vendors_description_fts'), 'vendors', [sa.literal_column("to_tsvector('english'::regconfig, COALESCE(description, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_vendor_categories_category_id'), 'vendor_categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_status_submitted'), 'approval_requests', ['status', 'submitted_date'], unique=False)
    op.create_table('customer_inquiries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('vendor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('customer_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('customer_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('preferred_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('expected_guests', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('budget_range', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('NEW', 'CONTACTED', 'QUOTED', 'CONVERTED', 'DECLINED', name='inquiry_status_enum'), server_default=sa.text("'NEW'::inquiry_status_enum"), autoincrement=False, nullable=False),
    sa.Column('vendor_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vendor_responded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('customer_inquiries_vendor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('customer_inquiries_pkey'))
    )
    op.create_index(op.f('ix_customer_inquiries_vendor_id_status'), 'customer_inquiries', ['vendor_id', 'status'], unique=False)
    op.create_index(op.f('ix_customer_inquiries_vendor_id'), 'customer_inquiries', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_customer_inquiries_customer_name'), 'customer_inquiries', ['customer_name'], unique=False)
    op.create_index(op.f('ix_customer_inquiries_customer_email'), 'customer_inquiries', ['customer_email'], unique=False)
    op.create_index(op.f('ix_customer_inquiries_created_at'), 'customer_inquiries', ['created_at'], unique=False)
    op.drop_index(op.f('ix_domain_events_event_type'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_correlation_id'), table_name='domain_events')
    op.drop_table('domain_events')
    # ### end Alembic commands ###
